name: Build VEH Patch DLLs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake (x64)
        run: cmake -S . -B build -A x64

      - name: Build DLLs
        run: cmake --build build --config Release

      - name: Debug - List build artifacts
        run: |
          echo "Listing all DLL files in build directory:"
          dir build\**\*.dll /s /b
        shell: cmd

      - name: Upload DLL artifacts
        uses: actions/upload-artifact@v4
        with:
          name: veh_patch_build
          path:
            # 修正YAML列表格式，确保每行缩进一致
            build/Release/*.dll
            build/**/Release/*.dll
