name: Build veh_patch DLLs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build DLL
      run: cmake --build build --config Release

    - name: Upload DLL artifacts
      uses: actions/upload-artifact@v4
      with:
        name: veh_patch_build
        path: build/**/*.dll
