name: Build veh_patch DLLs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 安装 CMake
        uses: lukka/get-cmake@v3.27.9

      - name: 配置 CMake
        run: cmake -S . -B build

      - name: 构建 DLL
        run: cmake --build build --config Release

      - name: 上传构建结果
        uses: actions/upload-artifact@v4
        with:
          name: veh_patch_build
          path: build/Release/*.dll
